#!/usr/bin/env bash

file=".coke"
params=""
options=""

standard=""

composerCommand="vendor/squizlabs/php_codesniffer/scripts/phpcs"

command="phpcs";
if [ -e "$composerCommand" ]
then
  command="$composerCommand"
fi

filesAllowed=""
filesIgnored=""

ignored=0
allowed=0
verbose=0

function allow
{
    if [ -z "$filesAllowed" ]
    then
        filesAllowed="$1"
    else
        filesAllowed="$filesAllowed $1"
    fi
}

function ignore
{
    if [ -z "$filesIgnored" ]
    then
        filesIgnored="$1"
    else
        filesIgnored="$filesIgnored,$1"
    fi
}

function success
{
    echo "[$(tput bold)$(tput setaf 2)SUCCESS$(tput sgr0)] $(tput setaf 6)$1$(tput sgr0)"
    exit 0
}

function fail
{
    echo "[$(tput bold)$(tput setaf 1)FAIL$(tput sgr0)] $(tput setaf 6)$1$(tput sgr0)"
    exit 1
}

function warning
{
    echo "[$(tput bold)$(tput setaf 3)WARNING$(tput sgr0)] $(tput setaf 6)$1$(tput sgr0)"
    exit 0
}

function info
{
    echo "[$(tput bold)$(tput setaf 4)INFO$(tput sgr0)] $(tput setaf 6)$1$(tput sgr0)"
}

# Résolution des options

while [ $# -ne 0 ]
do
    CUR_PARAM="$1"

    if [ "${CUR_PARAM:0:2}" =  "--" ]            # it's a parameter
    then
        if [ "${CUR_PARAM:2:9}" =  "standard=" ]
        then
            standard="${CUR_PARAM:11}"
        elif [ "${CUR_PARAM:2:7}" =  "ignore=" ]
        then
            ignore "${CUR_PARAM:9}"
            ignored=1
        else
            params="$params $CUR_PARAM"
        fi
    elif [ "${CUR_PARAM:0:1}" = "-" ]            # it's an option
    then
        case "${CUR_PARAM:1:1}" in
            v)
                verbose=1
            ;;
        esac

        options="$options ${CUR_PARAM}"
    else                                         # it's a file
        allow "$CUR_PARAM"
        allowed=1
    fi

    shift
done

# Resolve files to test

if [ -e "$file" ]
then
    output=$( grep "^[^\#]" $file )

    for ligne in $output
    do
        if [ "${ligne:0:8}" = "command=" ]
        then
            command="${ligne:8}"
        elif [ -z "$standard" ] && [ "${ligne:0:9}" = "standard=" ]
        then
            standard="${ligne:9}"
        elif  [ "$verbose" -eq 0 ] && [ "${ligne:0:8}" = "verbose=" ] && [ "${ligne:8}" = "true" ]
        then
            verbose=1
        elif [ "$ignored" -eq 0 ] && [ "${ligne:0:1}" = "!" ]
        then
            ignore "${ligne:1}"
        elif [ "$allowed" -eq 0 ] && [ -n "$ligne" ]
        then
            allow "$ligne"
        fi
    done
else
    warning "No config file found"
fi

if [ "$verbose" -eq 1 ]
then
    info "Starting sniffing"
fi

# Prepare command

if [ -n "$filesIgnored" ]
then
    filesIgnored="--ignore=$filesIgnored"
fi

if [ -n "$standard" ]
then
    standard="--standard=$standard"
else
    fail "No coding standard definition provided"
fi

# Punch it!

if [ -n "$filesAllowed" ]
then
    $command $filesAllowed $filesIgnored $standard $options $params

    if [ $? -ne 0 ]
    then
        fail "Some files do not match with \"${standard:11}\" requirements"
    fi
else
    warning "There was no file to test"
fi

success "All files match with \"${standard:11}\" requirements"
